### ISSUE TITLE
HistoryEditor的选中背景只考虑了单字节宽度，中文选中只有一半的背景

### ISSUE THREAD

**Issue by gongjianbo** [mengps/QmlControls#3]
![image](https://user-images.githubusercontent.com/31556155/216502488-b59010c3-4321-4b0c-825a-cf31787d56fe.png)
如图所示

**Comment by mengps** [comment]
因为这个项目其实应该叫做 example 而不应该叫 controls，不完善的地方太多，主要是以前写的，比较随意🥲。
