### ISSUE TITLE
你的无边框存在问题，当背景色设置成透明的时候，依然有黑色背景，经过分析，需要添加这段代码

### ISSUE THREAD

**Issue by wszx123123** [mengps/QmlControls#7]
#include <QSurfaceFormat>
    QSurfaceFormat format = QSurfaceFormat::defaultFormat();
    format.setAlphaBufferSize(8); // 设置alpha缓冲区以支持透明度
    QSurfaceFormat::setDefaultFormat(format);
完整代码如下
int main(int argc, char *argv[])
{
    QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);

    QSurfaceFormat format = QSurfaceFormat::defaultFormat();
    format.setAlphaBufferSize(8); // 设置alpha缓冲区以支持透明度
    QSurfaceFormat::setDefaultFormat(format);

    QGuiApplication app(argc, argv);

    qmlRegisterType<FramelessWindow>("an.window", 1, 0, "FramelessWindow");

    QQmlApplicationEngine engine;
    const QUrl url(QStringLiteral("qrc:/main.qml"));
    QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                     &app, [url](QObject *obj, const QUrl &objUrl) {
        if (!obj && url == objUrl)
            QCoreApplication::exit(-1);
    }, Qt::QueuedConnection);
    engine.load(url);

    return app.exec();
}

FramelessWindow {
    id: root
    visible: true
    width: 640
    height: 480
    minimumWidth: 480
    minimumHeight: 320
    color: "transparent"
    title: qsTr("Hello World")
    resizable: true

**Comment by wszx123123** [comment]
变成透明后可以自由的添加阴影，对应阴影代码（局部），我用另外这个无边框方案还存在垮屏幕拖拽时，整体下沉的问题，暂时还没有找到解决方案
    // 左边缘及上边缘阴影
    DropShadow {
        anchors.fill: mainWindow
        horizontalOffset: -5
        verticalOffset: -5
        radius: 12.0
        samples: 25
        color: "#20000000"
        spread: 0.0
        source: mainWindow
    }
    // 右边缘及下边缘阴影
    DropShadow {
        anchors.fill: mainWindow
        horizontalOffset: 5
        verticalOffset: 5
        radius: 12.0
        samples: 25
        color: "#20000000"
        spread: 0.0
        source: mainWindow
    }

**Comment by mengps** [comment]
已修复背景透明依旧为黑色的问题。
至于边缘阴影这些，我的本意是提供最简单无边框窗口实现，因为更多的功能应该视需求决定。
如果需要仿原生/边缘阴影/毛玻璃这些，其实可以选择更好的开源实现，例如：https://github.com/wangwenx190/framelesshelper和https://github.com/stdware/qwindowkit。
